// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO-Vomzud1P94_Kr3xPerM0XggX7TZq04',
    appId: '1:963036948422:web:2229effd05ac29b21234c7',
    messagingSenderId: '963036948422',
    projectId: 'ayobisa-e14c1',
    authDomain: 'ayobisa-e14c1.firebaseapp.com',
    storageBucket: 'ayobisa-e14c1.appspot.com',
    measurementId: 'G-PD6SH1YDXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbhhxgUbFjDYVjTf5u0UISFw6aFJ6YKp4',
    appId: '1:963036948422:android:22f115760721e0de1234c7',
    messagingSenderId: '963036948422',
    projectId: 'ayobisa-e14c1',
    storageBucket: 'ayobisa-e14c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByXgJVM74cSC3BVIs3fMH6OYhTbfdbAKo',
    appId: '1:963036948422:ios:425a059029cd916f1234c7',
    messagingSenderId: '963036948422',
    projectId: 'ayobisa-e14c1',
    storageBucket: 'ayobisa-e14c1.appspot.com',
    iosBundleId: 'com.example.cakeBaru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByXgJVM74cSC3BVIs3fMH6OYhTbfdbAKo',
    appId: '1:963036948422:ios:1fc770479d9c5e631234c7',
    messagingSenderId: '963036948422',
    projectId: 'ayobisa-e14c1',
    storageBucket: 'ayobisa-e14c1.appspot.com',
    iosBundleId: 'com.example.cakeBaru.RunnerTests',
  );
}
